### ISSUE TITLE
[Question] RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?

### ISSUE THREAD

**Issue by sabatale** [Datlyfe/jira_clone#14]
This is really more of a question. I'm not familiar with typeorm but I'm guessing the error is related to that module: `RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?`

Is there any reason why this happns to me when running the docker-compose file as-is? I have no issues with a manually installed PostgreSQL DB (after running `psql -d dbname -U user -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"` - this may be useful to some).

**Comment by Datlyfe** [comment]
@sabatale  In my experience `RepositoryNotFoundError` happens when you forget to register an entity in the entities array but that should not be the case.  it can happen in other cases too.
Not sure about why docker is not working for you but you since you have a local Postgres db it might be because of port conflicts maybe port 5432 is taken  try changing the ports in docker-compose.yml

**Comment by Scorfly** [comment]
Hi,

For your information i had to update the pg dependancies to : ^8.7.3 to make it work in docker *
